force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <description>A custom object that holds information about snowboard inventory.</description>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The list price of the board</description>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/Boardstore_Cart__c.object-meta.xml
<CustomObject>
    <description>This is the header object for the shopping cart of the boardstore.</description>
    <label>Boardstore Cart</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Boardstore Cart Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boardstore Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boardstore_Cart__c/fields/Cart_Status__c.field-meta.xml
<CustomField>
    <fullName>Cart_Status__c</fullName>
    <description>The status of the cart is used to apply logic relating to the progress of each cart, like abandonment for example.</description>
    <label>Cart Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Order - Processing</fullName>
            </value>
            <value>
                <fullName>Order - Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/Cart_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Cart_Subtotal__c</fullName>
    <description>The sum of line subtotals</description>
    <label>Cart Subtotal</label>
    <summarizedField>Boardstore_Cart_Line__c.Subtotal__c</summarizedField>
    <summaryForeignKey>Boardstore_Cart_Line__c.Boardstore_Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/Cart_Total__c.field-meta.xml
<CustomField>
    <fullName>Cart_Total__c</fullName>
    <label>Cart Total</label>
    <summarizedField>Boardstore_Cart_Line__c.Subtotal__c</summarizedField>
    <summaryForeignKey>Boardstore_Cart_Line__c.Boardstore_Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <description>This is the initial date that created the cart, used for calculations on abandonment</description>
    <label>Date Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/Shipping_Details_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Details_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipping Details Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/Shipping_Post_Code_Zip__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Post_Code_Zip__c</fullName>
    <label>Shipping Post Code / Zip</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/Total_Items__c.field-meta.xml
<CustomField>
    <fullName>Total_Items__c</fullName>
    <description>This is the count of the number of items in the cart</description>
    <label>Total Items</label>
    <summaryForeignKey>Boardstore_Cart_Line__c.Boardstore_Cart__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/Boardstore_Cart_Line__c.object-meta.xml
<CustomObject>
    <label>Boardstore Cart Line</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>Cart Line Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boardstore Cart Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <description>The snowboard selected</description>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Boardstore Cart Lines</relationshipLabel>
    <relationshipName>Boardstore_Cart_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Boardstore_Cart__c.field-meta.xml
<CustomField>
    <fullName>Boardstore_Cart__c</fullName>
    <label>Boardstore Cart</label>
    <referenceTo>Boardstore_Cart__c</referenceTo>
    <relationshipLabel>Boardstore Cart Lines</relationshipLabel>
    <relationshipName>Boardstore_Cart_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>This is a value that is inserted (as opposed to referenced) here as the price may change on the board after the cart is created/completed.</description>
    <label>Price</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The number of boards being purchased</description>
    <label>Quantity</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BoardCartController.cls
public with sharing class BoardCartController {
    @AuraEnabled
    public static BoardCartResult getCartHeader(String userId){
        // this method takes the user id and returns either
        // the current open Cart Header record or, if no open carts
        // exist, creates a new one and returns that. 
        List<Boardstore_Cart__c> currentCarts = new List<Boardstore_Cart__c>(
                                            [SELECT Id, Name, Date_Created__c, Cart_Status__c, Cart_Subtotal__c, Total_Items__c,
                                                    Shipping_Street__c, Shipping_City__c, Shipping_Post_Code_Zip__c, Shipping_Country__c,
                                                    Shipping_Details_Confirmed__c,  Tax__c, Cart_Total__c
                                            FROM Boardstore_Cart__c 
                                            WHERE ownerId =: userId 
                                            AND  Cart_Status__c = 'Open'
                                            LIMIT 1]);
        if(currentCarts.isEmpty()) {
            // create a new cart and return that
            Boardstore_Cart__c singleToCreate = new Boardstore_Cart__c();
            singleToCreate.Date_Created__c = System.Datetime.now();
            singleToCreate.Cart_Status__c = 'Open';
            singleToCreate.ownerId = userId;
            
            // Insert into database
            try {
                Database.SaveResult results = Database.insert(singleToCreate);
            } catch(DmlException e) {
                System.debug('DML Exception thrown: ' + e.getMessage());
            }
            // TODO: add default shipping fields.
            // reset current carts
            currentCarts = [SELECT Id, Name, Date_Created__c, Cart_Status__c, Cart_Subtotal__c, Total_Items__c,
                                    Shipping_Street__c, Shipping_City__c, Shipping_Post_Code_Zip__c, Shipping_Country__c,
                                    Shipping_Details_Confirmed__c  
                            FROM Boardstore_Cart__c 
                            WHERE ownerId =: userId 
                            AND  Cart_Status__c = 'Open'
                            LIMIT 1];
        } 
        // create a new instance of the BoardCartResult object
        BoardCartResult cartResult = new BoardCartResult();
        cartResult.cartHeader = currentCarts[0];
        
        // now check all the lines in that cart
        cartResult.cartLines = [SELECT Id, Name, Board__r.Name, Price__c, Quantity__c
                                FROM Boardstore_Cart_Line__c
                                WHERE Boardstore_Cart__c =: cartResult.cartHeader.Id];

        return cartResult;

    }
}