force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <description>A custom object that holds information about snowboard inventory.</description>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The list price of the board</description>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/Boardstore_Cart__c.object-meta.xml
<CustomObject>
    <description>This is the header object for the shopping cart of the boardstore.</description>
    <label>Boardstore Cart</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Boardstore Cart Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boardstore Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boardstore_Cart__c/fields/Cart_Status__c.field-meta.xml
<CustomField>
    <fullName>Cart_Status__c</fullName>
    <description>The status of the cart is used to apply logic relating to the progress of each cart, like abandonment for example.</description>
    <label>Cart Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Order - Processing</fullName>
            </value>
            <value>
                <fullName>Order - Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boardstore_Cart__c/fields/User_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>User_Tax_Rate__c</fullName>
    <label>User Tax Rate</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/Boardstore_Cart_Line__c.object-meta.xml
<CustomObject>
    <label>Boardstore Cart Line</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>Cart Line Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boardstore Cart Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <description>The snowboard selected</description>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Boardstore Cart Lines</relationshipLabel>
    <relationshipName>Boardstore_Cart_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Boardstore_Cart__c.field-meta.xml
<CustomField>
    <fullName>Boardstore_Cart__c</fullName>
    <label>Boardstore Cart</label>
    <referenceTo>Boardstore_Cart__c</referenceTo>
    <relationshipLabel>Boardstore Cart Lines</relationshipLabel>
    <relationshipName>Boardstore_Cart_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>This is a value that is inserted (as opposed to referenced) here as the price may change on the board after the cart is created/completed.</description>
    <label>Price</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Boardstore_Cart_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>The number of boards being purchased</description>
    <label>Quantity</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BoardstoreCartTriggerTest.cls
/**
 * Test Class to test the BoardstoreCartTrigger and BoardstoreCartLineTrigger
 * 
 */
@isTest
private class BoardstoreCartTriggerTest {

    // @isTest
    // static void defaultTax() {
    //     // create a cart record and check that it's there with 10% tax rate without the custom metadata record
    //     Boardstore_Cart__c cart = new Boardstore_Cart__c();
    //     cart.Cart_Status__c = 'Open';

    //     insert cart;
    //     System.assertEquals(10.00, [SELECT User_Tax_Rate__c FROM Boardstore_Cart__c WHERE Id = :cart.Id].User_Tax_Rate__c);
    // }

    @isTest
    static void usTax() {
        // create US user
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserName=uniqueUserName);

        System.runAs(u) {
            Boardstore_Cart__c cart = new Boardstore_Cart__c();
            cart.Cart_Status__c = 'Open';

            insert cart;
            System.assertEquals(15.00, [SELECT User_Tax_Rate__c FROM Boardstore_Cart__c WHERE Id = :cart.Id].User_Tax_Rate__c);
        }
    }

    @isTest
    static void lineUpdateResetsTax() {
        // create US user
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserName=uniqueUserName);

        System.runAs(u) {
        // create a cart record
        Boardstore_Cart__c cart = new Boardstore_Cart__c();
        cart.Cart_Status__c = 'Open';
        insert cart;
        
        // create a board
        Board__c board = new Board__c();
        board.Name = 'Test Board';
        board.Price__c = 100.00;
        insert board;

        // insert a line
        Boardstore_Cart_Line__c line = new Boardstore_Cart_Line__c();
        line.Board__c = board.Id;
        line.Quantity__c = 1;
        line.Boardstore_Cart__c = cart.Id;
        line.Price__c = board.Price__c;
        insert line;

        // update the line to trigger the line update
        line.Quantity__c = 2;
        update line;
        
        // check that the tax rate is 15%
        System.assertEquals(15.00, [SELECT User_Tax_Rate__c FROM Boardstore_Cart__c WHERE Id = :cart.Id].User_Tax_Rate__c);
        }
    }
}