force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <description>A custom object that holds information about snowboard inventory.</description>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/Ability_Level__c.field-meta.xml
<CustomField>
    <fullName>Ability_Level__c</fullName>
    <label>Ability Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Entry Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Board__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <label>Base</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Board_Notes__c.field-meta.xml
<CustomField>
    <fullName>Board_Notes__c</fullName>
    <label>Board Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Camber__c.field-meta.xml
<CustomField>
    <fullName>Camber__c</fullName>
    <description>Snowboard record type specific</description>
    <label>Camber</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Camber</fullName>
            </value>
            <value>
                <fullName>Rocker</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Flat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Board__c/fields/Core__c.field-meta.xml
<CustomField>
    <fullName>Core__c</fullName>
    <description>Core material of the board, for inclusion in the search filters</description>
    <label>Core</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Flex__c.field-meta.xml
<CustomField>
    <fullName>Flex__c</fullName>
    <label>Flex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stiff</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Soft</fullName>
            </value>
            <value>
                <fullName>Medium/Stiff</fullName>
            </value>
            <value>
                <fullName>Soft/Medium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Board__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <label>Image Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Mounting_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Mounting_Pattern__c</fullName>
    <description>Snowboard specific field</description>
    <label>Mounting Pattern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2x4</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>No Binding</fullName>
            </value>
            <value>
                <fullName>4x4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Board__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The list price of the board</description>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Shape__c.field-meta.xml
<CustomField>
    <fullName>Shape__c</fullName>
    <description>Board shape, will be used in the filters for the store component. Filters will use a fuzzy search to get multiple types</description>
    <label>Shape</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Sidecut__c.field-meta.xml
<CustomField>
    <fullName>Sidecut__c</fullName>
    <label>Sidecut</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Sidewall__c.field-meta.xml
<CustomField>
    <fullName>Sidewall__c</fullName>
    <label>Sidewall</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>Lists the sizes available for the board</description>
    <label>Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Snowboard_Type__c.field-meta.xml
<CustomField>
    <fullName>Snowboard_Type__c</fullName>
    <description>This is the type of snowboard, for the snowboard record type only.</description>
    <label>Snowboard Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Stance_Setback__c.field-meta.xml
<CustomField>
    <fullName>Stance_Setback__c</fullName>
    <label>Stance Setback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Midwide</fullName>
            </value>
            <value>
                <fullName>Wide</fullName>
            </value>
            <value>
                <fullName>Wide, Midwide, Regular</fullName>
            </value>
            <value>
                <fullName>Wide, Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BoardstoreController.cls
public with sharing class BoardstoreController {

    static Integer PAGE_SIZE = 9;

    // need to come back and fix these for the filters
    public class Filters {
        public String searchKey { get; set; }

        public Decimal maxPrice { get; set; }

        public String[] width { get; set; }

        public String[] flex { get; set; }

        public String[] camber { get; set; }

        public String[] mountingPattern { get; set; }
    }

    @AuraEnabled(Cacheable=true)
    public static PagedResult getBoards(String filters, Integer pageNumber){
        System.debug('the filters are: ' + filters);
        System.debug('the pageNumber is: ' + pageNumber);
        String searchString, whereClause = '';
        Decimal maxPrice;
        String[] width, flex, camber, mountingPattern, criteria = new String[]{};
        if(!String.isEmpty(filters)) {
            Filters productFilters = (Filters) JSON.deserializeStrict(filters, BoardstoreController.Filters.class);
            maxPrice = productFilters.maxPrice;
            if(!String.isEmpty(productFilters.searchKey)) {
                searchString = '%' + productFilters.searchKey + '%';
                criteria.add('Name LIKE :searchString');
            }
            // we want shape, camber, width and flex
            if(productFilters.maxPrice >= 0) {
                maxPrice = productFilters.maxPrice;
                criteria.add('Price__c <= :maxPrice');
            }
            if(productFilters.width != NULL) {
                width = productFilters.width;
                criteria.add('Width__c IN :width');
            }if(productFilters.flex != NULL) {
                flex = productFilters.flex;
                criteria.add('Flex__c IN :flex');
            }if(productFilters.camber != NULL) {
                camber = productFilters.camber;
                criteria.add('Camber__c IN :camber');
            }if(productFilters.mountingPattern != NULL) {
                mountingPattern = productFilters.mountingPattern;
                criteria.add('Mounting_Pattern__c IN :mountingPattern');
            }
            if(criteria.size() > 0 ) {
                whereClause = 'WHERE ' + String.join(criteria, ' AND ');
            }
        }

        String dbQuery = 'SELECT Id, Name, Ability_Level__c, Base__c, Board_Notes__c, Camber__c, Core__c, Description__c, Flex__c, Image_Name__c, Mounting_Pattern__c, Price__c, Shape__c, Sidecut__c, Sidewall__c, Size__c, Snowboard_Type__c, Stance_Setback__c, Width__c from Board__c ' + whereClause + ' ORDER BY Name LIMIT :pageSize OFFSET :offset';
        String countQuery = 'SELECT count() from Board__c ' + whereClause;
        Integer pageSize = BoardstoreController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PagedResult result = new PagedResult();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        System.debug('count query is: ' + countQuery);
        result.totalItemCount = Database.countQuery(countQuery);
        result.records = Database.query(dbQuery);
        return result;
    }
}