force-app/main/default/objects/Boardstore_Cart__c/Boardstore_Cart__c.object-meta.xml
<CustomObject>
    <description>This is the header object for the shopping cart of the boardstore.</description>
    <label>Boardstore Cart</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Boardstore Cart Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boardstore Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boardstore_Cart__c/fields/User_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>User_Tax_Rate__c</fullName>
    <label>User Tax Rate</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__mdt/Tax_Rate__mdt.object-meta.xml
<CustomObject>
    <description>This is where the tax rates are going to be stored</description>
    <label>Tax Rate</label>
    <pluralLabel>Tax Rates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Rate__mdt/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/CartHeaderTaxUtil.cls
public with sharing class CartHeaderTaxUtil {
    public static void updateCartTaxRate(Map<Id, String> carts) {
        // Create list of cart Ids to update
        List<Boardstore_Cart__c> cartList = new List<Boardstore_Cart__c>();

        // loop through the map
        for (Id cartId : carts.keySet()) {
            // Get the cart
            Boardstore_Cart__c cart = new Boardstore_Cart__c(Id = cartId);
            // Get the tax rate
            Decimal taxRate = [SELECT Tax_Rate__c FROM Tax_Rate__mdt WHERE DeveloperName =: carts.get(cartId) LIMIT 1].Tax_Rate__c;
            // Set the tax rate
            cart.User_Tax_Rate__c = taxRate;
            // Add the cart to the list
            cartList.add(cart);
        }
        update cartList;
    }
}